### ISSUE TITLE
Support for Custom Variables

### ISSUE THREAD

**Issue by WestbamChamsys** [bitfocus/companion-module-chamsys-magicq-osc#10]
When using any custom variable to send to Chamsys MagicQ, the contents of the "value" field turns red, and companion only send a zero, regardless what I try.

Would be really handy if we can, just like in the real OSC module,  send Custom variables so we can do some logic on the stream deck.

Thnaks for reading.

**Comment by josephdadams** [comment]
added in v2.1.0 of the module
